language: java
jdk: oraclejdk8
notifications:
  email: false
env:
  global:
  - TERM=dumb

before_install: openssl aes-256-cbc -K $encrypted_e7b4c51e5166_key -iv $encrypted_e7b4c51e5166_iv -in keystore.jks.enc -out keystore.jks -d
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock

branches:
  except:
  - /^release-.*$/

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew curseforge -S
    on:
      all_branches: true
      repo: CyclopsMC/EnergeticSheep
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: ZH6b0OTJeBXrhy1tJLFdHO+rIW27q5d1tFCgaNarEFE+kJSVEiKtrGi+TBTpCRJVdPiMtTZR5t6MDaZ7xNWC4Bu7N+FEr4UHRiljMzMn/SGDVMLWvx+Q+roFqs9KzjtG2N37QkxQdDIQdcEl9rSS15yyCvz2oFaY9va8GrEiszlW4/VVW8hju5S+n1AP9nXPbwF17I84dq7LCbLKaUTZ/MSFcTB64XrMj0BLiWi3KEHfSoyk9bJ0tYjLcA81qX7ivaQW7jS4kf0JnHkDBE6hPvmkMD1mvUJndZa3HjxUIk4ExvmJqKhGPJW7SRdnv2d5GJL5zYmFubF3qgx3ZUQ95jCEPMYz0T2g0/696kQBmU3GeiUFiJhon+qoDfqFLxoB38ZTaIFPBBTl/xrgmKAuJZGUefzsWJf8d6liE8YOEYdI1cYz89aFYsv9FwLMHCFj8H9jI/oBoORzahVpAXyiAw4VQ1Cm15HQZdVv1Frwe+F01u8DEq/AoyyoP5LcDzYOQgSVDs6zv8nEthBTmJ72fatMXVo/EYNLXY21mJePOG5p9lddjBloCJac1kg2jruo6dSxrOTU6w67WtZEpQ28eTF2LBsZ4vAjcYxksZQOPBwjY5biH9EP9NvepTkUfoynoi9BwMucIxmEGSMtzxcwOjZFHsaycaCkFpXG8lQn740=
    on:
      all_branches: true
      repo: CyclopsMC/EnergeticSheep
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./gradlew uploadArchives -S
    on:
      all_branches: true
      repo: CyclopsMC/EnergeticSheep
      condition: "$TRAVIS_BRANCH =~ ^(master|release).*$"
