modLoader="javafml"
loaderVersion="[31.1,)"
issueTrackerURL="https://github.com/CyclopsMC/EnergeticSheep/issues"
[[mods]]
modId="energeticsheep"
version="${file.jarVersion}"
displayName="EnergeticSheep"
displayURL="https://www.curseforge.com/minecraft/mc-mods/energeticsheep"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
description='''
Sheep that generate energy
'''
[[dependencies.energeticsheep]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.9.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.energeticsheep]]
    modId="forge"
    mandatory=true
    versionRange="[31.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.energeticsheep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
